Content:
    type: object
    config:
        description: "An eZ Platform repository Content."
        fields:
            contentInfo:
                type: "ContentInfo"
                description: "The Content item's unique ID."
            id:
                type: "Int"
                description: "Shortcut to contentInfo.id."
            fields:
                type: "[Field]"
                description: "The Content item's Fields."
                args:
                    identifier:
                        description: "Filter by field def identifier"
                        type: "String"
                resolve: "@=resolver('ContentFields', [value, args])"
ContentCreateStruct:
    type: object
    config:
        description: "A new content item."
        fields:
            contentTypeId:
                type: "Int"
                description: "The Content item's Content Type ID."
            sectionId:
                type: "Int"
                description: "The Section id the Content item must be assigned."
            ownerId:
                type: "Int"
                description: "The owner of the content. If not given the current authenticated user is set as owner."
            alwaysAvailable:
                type: "Boolean"
                description: "Indicates if the content object is shown in the mainlanguage if its not present in an other requested language."
            remoteId:
                type: "String"
                description: "Remote identifier used as a custom identifier for the object."
            mainLanguageCode:
                type: "String"
                description: "The main language code for the content."
            modificationDate:
                type: "String"
                description: "Modification date. If not given the current timestamp is used."
            fields:
                type: "[Field]"
                description: "The Content fields"
