Query:
    type: object
    config:
        description: "eZ Platform repository"
        fields:
            location:
                type: "Location"
                args:
                    id:
                        description: "Resolves using the unique location id."
                        type: "Int"
                resolve: "@=resolver('Location', [args])"
            content:
                type: "Content"
                args:
                    id:
                        description: "Resolves using the unique Content id."
                        type: "Int"
                    remoteId:
                        description: "Resolves using the unique Content remote id."
                        type: "String"
                resolve: "@=resolver('Content', [args])"
            user:
                type: "User"
                args:
                    id:
                        description: "Load user by ID."
                        type: "Int"
                    email:
                        description: "Load user by email address."
                        type: "Int"
                    login:
                        description: "Load user by login."
                        type: "Int"
                resolve: "@=resolver('User', [args])"
            contentType:
                type: "ContentType"
                args:
                    id:
                        description: "Resolves using the unique ContentType id."
                        type: "Int"
                    identifier:
                        description: "Resolves using the unique ContentType identifier."
                        type: "String"
                resolve: "@=resolver('ContentType', [args])"
            locationChildren:
                type: "[Location]"
                args:
                    id:
                        description: "ID of the Location to get children for"
                        type: "Int"
                resolve: "@=resolver('LocationChildren', [args])"
            contentTypes:
                type: "[ContentType]"
                args:
                    groupId:
                        type: "String"
                    groupIdentifier:
                        type: "String"
                resolve: "@=resolver('ContentTypesFromGroup', [args])"
